// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notification.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Notification module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Notification_OpenAssociatedRequestBuilder(
		notification.proxies.Notification _notification
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notification.ACT_Notification_OpenAssociatedRequest");
		builder = builder.withParam("Notification", _notification);
		return builder;
	}

	public static void aCT_Notification_OpenAssociatedRequest(
		IContext context,
		notification.proxies.Notification _notification
	)
	{
		aCT_Notification_OpenAssociatedRequestBuilder(
				_notification
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Notification_SetToReadBuilder(
		notification.proxies.Notification _notification
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notification.ACT_Notification_SetToRead");
		builder = builder.withParam("Notification", _notification);
		return builder;
	}

	public static void aCT_Notification_SetToRead(
		IContext context,
		notification.proxies.Notification _notification
	)
	{
		aCT_Notification_SetToReadBuilder(
				_notification
			)
			.execute(context);
	}
}
