// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expenses.proxies;

public class HeaderData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject headerDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Expenses.HeaderData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AmountSubmitted("AmountSubmitted"),
		AmountApproved("AmountApproved"),
		HeaderData_Session("Expenses.HeaderData_Session");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HeaderData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected HeaderData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject headerDataMendixObject)
	{
		if (headerDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, headerDataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.headerDataMendixObject = headerDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static expenses.proxies.HeaderData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new expenses.proxies.HeaderData(context, mendixObject);
	}

	public static expenses.proxies.HeaderData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return expenses.proxies.HeaderData.initialize(context, mendixObject);
	}

	/**
	 * @return value of AmountSubmitted
	 */
	public final java.math.BigDecimal getAmountSubmitted()
	{
		return getAmountSubmitted(getContext());
	}

	/**
	 * @param context
	 * @return value of AmountSubmitted
	 */
	public final java.math.BigDecimal getAmountSubmitted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AmountSubmitted.toString());
	}

	/**
	 * Set value of AmountSubmitted
	 * @param amountsubmitted
	 */
	public final void setAmountSubmitted(java.math.BigDecimal amountsubmitted)
	{
		setAmountSubmitted(getContext(), amountsubmitted);
	}

	/**
	 * Set value of AmountSubmitted
	 * @param context
	 * @param amountsubmitted
	 */
	public final void setAmountSubmitted(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amountsubmitted)
	{
		getMendixObject().setValue(context, MemberNames.AmountSubmitted.toString(), amountsubmitted);
	}

	/**
	 * @return value of AmountApproved
	 */
	public final java.math.BigDecimal getAmountApproved()
	{
		return getAmountApproved(getContext());
	}

	/**
	 * @param context
	 * @return value of AmountApproved
	 */
	public final java.math.BigDecimal getAmountApproved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AmountApproved.toString());
	}

	/**
	 * Set value of AmountApproved
	 * @param amountapproved
	 */
	public final void setAmountApproved(java.math.BigDecimal amountapproved)
	{
		setAmountApproved(getContext(), amountapproved);
	}

	/**
	 * Set value of AmountApproved
	 * @param context
	 * @param amountapproved
	 */
	public final void setAmountApproved(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amountapproved)
	{
		getMendixObject().setValue(context, MemberNames.AmountApproved.toString(), amountapproved);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of HeaderData_Session
	 */
	public final system.proxies.Session getHeaderData_Session() throws com.mendix.core.CoreException
	{
		return getHeaderData_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of HeaderData_Session
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Session getHeaderData_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HeaderData_Session.toString());
		if (identifier != null) {
			result = system.proxies.Session.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of HeaderData_Session
	 * @param headerdata_session
	 */
	public final void setHeaderData_Session(system.proxies.Session headerdata_session)
	{
		setHeaderData_Session(getContext(), headerdata_session);
	}

	/**
	 * Set value of HeaderData_Session
	 * @param context
	 * @param headerdata_session
	 */
	public final void setHeaderData_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session headerdata_session)
	{
		if (headerdata_session == null) {
			getMendixObject().setValue(context, MemberNames.HeaderData_Session.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.HeaderData_Session.toString(), headerdata_session.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return headerDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final expenses.proxies.HeaderData that = (expenses.proxies.HeaderData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
