// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expenses.proxies;

public class Request implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Expenses.Request";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Status("Status"),
		Location("Location"),
		TotalAmount("TotalAmount"),
		RequestID("RequestID"),
		Request_Project("Expenses.Request_Project");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Request(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Request(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject)
	{
		if (requestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, requestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.requestMendixObject = requestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static expenses.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new expenses.proxies.Request(context, mendixObject);
	}

	public static expenses.proxies.Request load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return expenses.proxies.Request.initialize(context, mendixObject);
	}

	public static java.util.List<expenses.proxies.Request> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> expenses.proxies.Request.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final expenses.proxies.ENUM_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final expenses.proxies.ENUM_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return expenses.proxies.ENUM_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(expenses.proxies.ENUM_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, expenses.proxies.ENUM_Status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * Get value of Location
	 * @param location
	 */
	public final expenses.proxies.ENUM_Location getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final expenses.proxies.ENUM_Location getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Location.toString());
		if (obj == null) {
			return null;
		}
		return expenses.proxies.ENUM_Location.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(expenses.proxies.ENUM_Location location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, expenses.proxies.ENUM_Location location)
	{
		if (location != null) {
			getMendixObject().setValue(context, MemberNames.Location.toString(), location.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Location.toString(), null);
		}
	}

	/**
	 * @return value of TotalAmount
	 */
	public final java.math.BigDecimal getTotalAmount()
	{
		return getTotalAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalAmount
	 */
	public final java.math.BigDecimal getTotalAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalAmount.toString());
	}

	/**
	 * Set value of TotalAmount
	 * @param totalamount
	 */
	public final void setTotalAmount(java.math.BigDecimal totalamount)
	{
		setTotalAmount(getContext(), totalamount);
	}

	/**
	 * Set value of TotalAmount
	 * @param context
	 * @param totalamount
	 */
	public final void setTotalAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalamount)
	{
		getMendixObject().setValue(context, MemberNames.TotalAmount.toString(), totalamount);
	}

	/**
	 * @return value of RequestID
	 */
	public final java.lang.Long getRequestID()
	{
		return getRequestID(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestID
	 */
	public final java.lang.Long getRequestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.RequestID.toString());
	}

	/**
	 * Set value of RequestID
	 * @param requestid
	 */
	public final void setRequestID(java.lang.Long requestid)
	{
		setRequestID(getContext(), requestid);
	}

	/**
	 * Set value of RequestID
	 * @param context
	 * @param requestid
	 */
	public final void setRequestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long requestid)
	{
		getMendixObject().setValue(context, MemberNames.RequestID.toString(), requestid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Request_Project
	 */
	public final java.util.List<expenses.proxies.Project> getRequest_Project() throws com.mendix.core.CoreException
	{
		return getRequest_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of Request_Project
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<expenses.proxies.Project> getRequest_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<expenses.proxies.Project> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Request_Project.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(expenses.proxies.Project.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Request_Project
	 * @param request_project
	 */
	public final void setRequest_Project(java.util.List<expenses.proxies.Project> request_project)
	{
		setRequest_Project(getContext(), request_project);
	}

	/**
	 * Set value of Request_Project
	 * @param context
	 * @param request_project
	 */
	public final void setRequest_Project(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<expenses.proxies.Project> request_project)
	{
		var identifiers = request_project
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Request_Project.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final expenses.proxies.Request that = (expenses.proxies.Request) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
