// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notification.proxies;

public class Notification implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject notificationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Notification.Notification";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Message("Message"),
		Read("Read"),
		AssociatedObject("AssociatedObject"),
		Notification_Account("Notification.Notification_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Notification(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Notification(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject notificationMendixObject)
	{
		if (notificationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, notificationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.notificationMendixObject = notificationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static notification.proxies.Notification initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new notification.proxies.Notification(context, mendixObject);
	}

	public static notification.proxies.Notification load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return notification.proxies.Notification.initialize(context, mendixObject);
	}

	public static java.util.List<notification.proxies.Notification> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> notification.proxies.Notification.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of Read
	 */
	public final java.lang.Boolean getRead()
	{
		return getRead(getContext());
	}

	/**
	 * @param context
	 * @return value of Read
	 */
	public final java.lang.Boolean getRead(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Read.toString());
	}

	/**
	 * Set value of Read
	 * @param read
	 */
	public final void setRead(java.lang.Boolean read)
	{
		setRead(getContext(), read);
	}

	/**
	 * Set value of Read
	 * @param context
	 * @param read
	 */
	public final void setRead(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean read)
	{
		getMendixObject().setValue(context, MemberNames.Read.toString(), read);
	}

	/**
	 * @return value of AssociatedObject
	 */
	public final java.lang.Long getAssociatedObject()
	{
		return getAssociatedObject(getContext());
	}

	/**
	 * @param context
	 * @return value of AssociatedObject
	 */
	public final java.lang.Long getAssociatedObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AssociatedObject.toString());
	}

	/**
	 * Set value of AssociatedObject
	 * @param associatedobject
	 */
	public final void setAssociatedObject(java.lang.Long associatedobject)
	{
		setAssociatedObject(getContext(), associatedobject);
	}

	/**
	 * Set value of AssociatedObject
	 * @param context
	 * @param associatedobject
	 */
	public final void setAssociatedObject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long associatedobject)
	{
		getMendixObject().setValue(context, MemberNames.AssociatedObject.toString(), associatedobject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Notification_Account
	 */
	public final java.util.List<administration.proxies.Account> getNotification_Account() throws com.mendix.core.CoreException
	{
		return getNotification_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Notification_Account
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<administration.proxies.Account> getNotification_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<administration.proxies.Account> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Notification_Account.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(administration.proxies.Account.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Notification_Account
	 * @param notification_account
	 */
	public final void setNotification_Account(java.util.List<administration.proxies.Account> notification_account)
	{
		setNotification_Account(getContext(), notification_account);
	}

	/**
	 * Set value of Notification_Account
	 * @param context
	 * @param notification_account
	 */
	public final void setNotification_Account(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<administration.proxies.Account> notification_account)
	{
		var identifiers = notification_account
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Notification_Account.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return notificationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final notification.proxies.Notification that = (notification.proxies.Notification) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
